### ISSUE TITLE
plugins or command snippets

### ISSUE THREAD

**Issue by vsoch** [compspec/jobspec#20]
## support for custom (commonly used) snippets

As part of work for usernetes, I am also anticipating wanting to make plugins or "ready to go" additions you can add on to a particular instance. For example, to make an instance "kubernetes ready" we would need to manually put all the commands in some bash script before using kubectl. If we are going to expose those easily to the user to interact with, we'd do better off having the tool set it up for is. 
Something like:

```yaml
groups:
 - name: ml-work
   resources: ml-group
   tasks:

   - name: start
     plugins: [start-usernetes]
     command: kubectl apply -f ./database.yaml

   - name: train
     depends_on: ["start"]
     replicas: 100
     resources: single-node
     command:
      - bash
      - -c
      - |
        ml-train ... -o train.json
        compspec save-artifact ./train.json --host http://localhost:8080

  - name: delete
    depends_on: ["test"]
    plugins: [stop-usernetes]
    command: kubectl delete -f ./database.yaml
```
